cfg_name: 'euroc'

# dataset
dataset: 'euroc'
num_scales: 3

# training
num_iterations: 200000


w_ssim: 0.85 # w_pixel = 1 - w_ssim
w_flow_smooth: 10.0
w_flow_consis: 0.01
w_geo: 0.1
w_pt_depth: 1.0
w_pj_depth: 0.1
w_flow_error: 0.0
w_depth_smooth: 0.0001


h_flow_consist_alpha: 3.0
h_flow_consist_beta: 0.05

ransac_iters: 100
ransac_points: 6000

# Depth Setting
depth_match_num: 6000
depth_sample_ratio: 0.20
depth_scale: 1

# basic info
img_hw: [256, 832]
block_tri_grad: False

